# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
# use this to find packages: https://anaconda.org/
name: qbic-pipelines-rnadeseq-1.3.0
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r-base=3.5.1
  - r::r-hexbin=1.27.2
  - conda-forge::r-svglite=1.2.3
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-gplots=3.0.3
  - bioconda::bioconductor-vsn=3.50.0
  - r::r-plyr=1.8.4
  - conda-forge::r-ggplot2=3.3.0
  - conda-forge::r-rcolorbrewer=1.1_2
  - bioconda::bioconductor-genefilter=1.64.0
  - bioconda::bioconductor-deseq2=1.22.1 #ResolvePackageNotFound error with version 1.22.2
  - bioconda::bioconductor-vsn=3.50.0
  - bioconda::bioconductor-genomeinfodbdata=1.2.1
  - conda-forge::cairo=1.16.0
  - conda-forge::r-optparse=1.6.4
  - conda-forge::r-extrafont=0.17
  - conda-forge::r-knitr=1.28
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-dt=0.13
  - r::r-yaml=2.2.0 # chose R channel because conda-forge has only 0.1.7
  - conda-forge::r-rmarkdown=2.1
  - bioconda::bioconductor-annotationdbi=1.44.0
  - conda-forge::r-reshape2=1.4.3
  - bioconda::bioconductor-pathview=1.22.0
  - bioconda::bioconductor-org.mm.eg.db=3.7.0
  - bioconda::bioconductor-org.hs.eg.db=3.7.0
  - bioconda::bioconductor-limma=3.38.3
  - r::r-dplyr=0.7.6
  - conda-forge::r-kableextra=1.1.0
  - conda-forge::r-formattable=0.2.0.1
  - conda-forge::r-gprofiler2=0.1.8
  - conda-forge::r-rlist=0.4.6.1
