# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
# use this to find packages: https://anaconda.org/
name: nf-core-rnadeseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r::r-hexbin=1.27.2
  - conda-forge::r-svglite=1.2.1
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-gplots=3.0.1.1
  - bioconda::bioconductor-vsn=3.50.0
  - r::r-plyr=1.8.4
  - conda-forge::r-ggplot2=3.1.1
