# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
# use this to find packages: https://anaconda.org/
name: qbicsoftware-rnadeseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
  - anaconda
dependencies:
  - r-base=3.5.1
  - r::r-hexbin
  - conda-forge::r-svglite
  - conda-forge::r-pheatmap
  - conda-forge::r-gplots
  - bioconda::bioconductor-vsn
  - r::r-plyr
  - conda-forge::r-ggplot2
  - conda-forge::r-rcolorbrewer
  - bioconda::bioconductor-genefilter
  - bioconda::bioconductor-deseq2=1.22.1 #ResolvePackageNotFound error with version 1.22.2
  - bioconda::bioconductor-vsn
  - bioconda::bioconductor-genomeinfodbdata
  - conda-forge::cairo
  - conda-forge::r-optparse
  - conda-forge::r-extrafont
# additional packages for the RNAseq report
  - conda-forge::r-knitr
  - conda-forge::r-tidyverse
  - conda-forge::r-dt
  - r::r-yaml # chose R channel because conda-forge has only 0.1.7
  - conda-forge::r-rmarkdown
# Additional packages for the gProfileR script
  - bioconda::bioconductor-annotationdbi
  - conda-forge::r-reshape2
  - bioconda::bioconductor-pathview
  - bioconda::bioconductor-org.mm.eg.db
  - bioconda::bioconductor-org.hs.eg.db
  - conda-forge::r-gprofiler
  - r::r-dplyr
