name: CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: 
  push:
  pull_request:
  release:
    types: [published]

jobs:
  test:
    name: Run workflow tests
    runs-on: ubuntu-latest
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['19.10.0', '']
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Check if Dockerfile or Conda environment changed
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
            Dockerfile
            environment.yml
      
      - name: Build new docker image
        if: env.GIT_DIFF
        run: docker build --no-cache . -t nfcore/bcellmagic:dev

      - name: Pull docker image
        if: ${{ !env.GIT_DIFF }}
        run: |
          docker pull qbicpipelines/rnadeseq:dev
          docker tag qbicpipelines/rnadeseq:dev qbicpipelines/rnadeseq:dev

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with test data
        run: nextflow run ${GITHUB_WORKSPACE} -profile test,docker
  
  parameters:
    name: Test workflow parameters
    runs-on: ubuntu-latest
    env: 
      NXF_VER: '19.10.0'
      NXF_ANSI_LOG: false
    strategy:
      matrix:
        config: ['test', 'test_contrast_matrix', 'test_contrast_list']
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2
      
      - name: Check if Dockerfile or Conda environment changed
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
          Dockerfile
          enfironment.yml
      
      - name: Build new docker image
        if: env.GIT_DIFF
        run: docker build --no-cache . -t nfcore/bcellmagic:dev

      - name: Pull docker image
        if: ${{ !env.GIT_DIFF }}
        run: |
          docker pull qbicpipelines/rnadeseq:dev
          docker tag qbicpipelines/rnadeseq:dev qbicpipelines/rnadeseq:dev

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with various parameters
        run: nextflow run ${GITHUB_WORKSPACE} -profile ${{ matrix.config }},docker